/* 実WordPressと本機Edgeで操作します。Studio応答だけは合成です。 */
const fs = require('node:fs');
const path = require('node:path');
const assert = require('node:assert/strict');
const {chromium} = require(process.env.FMI_PLAYWRIGHT_MODULE || '../../../app/node_modules/playwright');
const fixture = JSON.parse(fs.readFileSync(process.argv[2], 'utf8').replace(/^\uFEFF/, ''));
const output = process.argv[3] || path.resolve(__dirname, '../docs/evidence');
fs.mkdirSync(output, {recursive: true});
(async () => {
  const browser = await chromium.launch({channel: 'msedge', headless: true});
  const errors = [], evidence = [], checks = [];
  let currentPage = null;
  const checked = (name) => { checks.push(name); console.log(name); };
  try {
    const context = await browser.newContext({viewport: {width: 1365, height: 1000}, colorScheme: 'light'});
    await context.addCookies(fixture.cookies);
    context.setDefaultTimeout(12000);
    const page = await context.newPage(); currentPage = page; page.on('pageerror', (error) => errors.push(error.message));
    page.on('response', async (reply) => { if (reply.url().includes('/staff/') && reply.status() >= 400) { const data = await reply.json(); console.log('REST確認:', reply.status(), data.message || data.state); } });
    const chat = page.locator('#fmi-chat'); const input = () => chat.locator('textarea');
    const assistants = () => chat.locator('.fmi-chat__message--assistant');
    const send = async (text) => { const before = await assistants().count(); await input().fill(text); await chat.getByRole('button', {name: '送信', exact: true}).click(); await page.waitForFunction((count) => document.querySelectorAll('#fmi-chat .fmi-chat__message--assistant').length > count && document.querySelector('#fmi-chat').getAttribute('aria-busy') === 'false', before); };
    const fit = async (locator) => { const sizes = await locator.evaluate((el) => ({width: el.clientWidth, scroll: el.scrollWidth})); assert.ok(sizes.scroll <= sizes.width + 1, JSON.stringify(sizes)); };
    const shot = async (name) => { await page.evaluate(() => window.scrollTo(0, 0)); await page.screenshot({path: path.join(output, name), fullPage: true}); evidence.push(name); };
    await page.goto('http://localhost:48093/wp-admin/admin.php?page=fourmix-intelligence-operations&post_id=' + fixture.draft_id);
    await page.getByRole('heading', {name: 'Fourmix Intelligence 運営支援'}).waitFor();
    const chatUrl = page.url();
    const settingsUrl = 'http://localhost:48093/wp-admin/admin.php?page=fourmix-intelligence-personal-settings';
    await page.goto(settingsUrl);
    await page.locator('#fmi-personal-token').fill('synthetic-ui-personal-token'); await page.getByRole('button', {name: 'AI一覧を取得'}).click();
    await page.locator('#fmi-personal-status').getByText('本人のAIに接続しました。').waitFor();
    await page.locator('#fmi-staff-agent').selectOption('synthetic-internal'); await page.locator('#fmi-personal-status').getByText('AIの選択を保存しました。').waitFor();
    assert.equal(await page.locator('#fmi-personal-token').inputValue(), ''); checked('本人トークン入力は接続後に消去');
    await page.goto(chatUrl); await input().waitFor();
    await input().fill('長文・運営相談');
    await chat.getByRole('button', {name: '送信', exact: true}).evaluate((el) => { el.click(); el.click(); });
    await assistants().first().waitFor(); assert.equal(await chat.locator('.fmi-chat__message--user').count(), 1); checked('二重クリックでメッセージを増やさない');
    assert.equal(await chat.locator('.fmi-chat__hint').filter({hasText: '画面情報は送信していません'}).count(), 1);
    await page.locator('#fmi-include-context').check(); await send('合成運営・続けて相談'); checked('複数ターンと投稿情報の送信選択');
    await send('合成操作・実行しない');
    const rejected = chat.locator('.fmi-chat__tool').first(); await rejected.getByRole('button', {name: '内容を確認して実行'}).waitFor();
    await page.waitForFunction(() => [...document.querySelectorAll('#fmi-chat .fmi-chat__tool button')].some((el) => el.textContent === '内容を確認して実行' && !el.disabled));
    await rejected.getByRole('button', {name: '今回は実行しない'}).click(); await rejected.getByText('この画面からは実行しません。', {exact: false}).waitFor(); checked('実行を見送る操作');
    await send('合成操作・確認する'); const approved = chat.locator('.fmi-chat__tool').last();
    assert.equal(await rejected.getByRole('button', {name: '内容を確認して実行', includeHidden: true}).isVisible(), false); checked('実行を見送ったカードは後続ターンでも復元しない');
    await approved.getByRole('button', {name: '内容を確認して実行'}).click(); await approved.getByText('実行済み', {exact: true}).waitFor(); checked('正式プレビューから明示確認と監査IDを表示');
    await fit(chat); await shot('chat-admin-desktop.png');
    await page.setViewportSize({width: 390, height: 844}); await fit(page.locator('body')); await fit(chat); await shot('chat-admin-narrow.png'); checked('390pxで横スクロールなし');
    await page.emulateMedia({colorScheme: 'dark'}); await shot('chat-admin-dark-narrow.png');
    await page.setViewportSize({width: 1365, height: 1000}); await page.emulateMedia({colorScheme: 'light'});
    await input().fill('合成遅延・受信停止'); await chat.getByRole('button', {name: '送信', exact: true}).click();
    await chat.getByRole('button', {name: '受信を停止', exact: true}).click(); await chat.getByText('受信を停止しました。', {exact: false}).waitFor();
    assert.equal(await chat.getByRole('button', {name: '送信', exact: true}).isDisabled(), true); await page.waitForTimeout(3500);
    await chat.getByRole('button', {name: '送信結果を確認'}).click(); await chat.getByText('応答を受け取りました。', {exact: true}).waitFor(); checked('受信停止は送信結果の照会で復旧');
    await input().fill('合成遅延・戻る操作'); await chat.getByRole('button', {name: '送信', exact: true}).click(); await chat.getByRole('button', {name: '受信を停止'}).waitFor();
    await page.goto('http://localhost:48093/wp-admin/profile.php'); await page.goBack(); await input().waitFor(); await chat.getByRole('button', {name: '送信結果を確認'}).waitFor(); await page.waitForTimeout(3500);
    await chat.getByRole('button', {name: '送信結果を確認'}).click(); await chat.getByText('応答を受け取りました。', {exact: true}).waitFor(); checked('戻る操作でも送信を再実行せず照会');
    await input().fill('合成遅延・画面を開き直す'); await input().press('Control+Enter'); await chat.getByRole('button', {name: '受信を停止'}).waitFor();
    await page.reload(); await input().waitFor(); await chat.getByRole('button', {name: '送信結果を確認'}).waitFor(); await page.waitForTimeout(3500);
    await chat.getByRole('button', {name: '送信結果を確認'}).click(); await chat.getByText('応答を受け取りました。', {exact: true}).waitFor(); checked('再読込後は自動再送せず結果照会');
    let aborted = false;
    await page.route('**/staff/chat_stream', async (route) => { if (!aborted) { aborted = true; await route.abort('failed'); } else await route.continue(); });
    await input().fill('合成未送信・回復'); await chat.getByRole('button', {name: '送信', exact: true}).click(); await chat.getByRole('button', {name: '送信結果を確認'}).waitFor();
    await chat.getByRole('button', {name: '送信結果を確認'}).click(); await chat.getByRole('button', {name: '同じ送信を再開'}).waitFor();
    await chat.getByRole('button', {name: '同じ送信を再開'}).click(); await chat.getByText('応答を受け取りました。', {exact: true}).waitFor(); await page.unroute('**/staff/chat_stream'); checked('未到達の送信は同じ確認情報で回復');
    await send('合成安全表示'); assert.equal(await chat.locator('img').count(), 0); assert.equal(await page.evaluate(() => window.fmiInjected), undefined); checked('HTMLは文字として安全に表示');
    await send('合成不明操作・UI'); const unknown = chat.locator('.fmi-chat__tool').last(); await unknown.getByRole('button', {name: '内容を確認して実行'}).click();
    await unknown.getByText('結果不明。', {exact: false}).waitFor(); assert.equal(await unknown.getByRole('button', {name: '内容を確認して実行', includeHidden: true}).isDisabled(), true);
    await unknown.getByRole('button', {name: '実行結果を確認'}).click(); await shot('chat-admin-unknown.png'); checked('結果不明は確認ボタンを無効にして状態照会のみ');
    const previous = await assistants().count(); await page.goto(settingsUrl); await page.locator('#fmi-staff-agent').selectOption('synthetic-second'); await page.locator('#fmi-personal-status').getByText('AIの選択を保存しました。').waitFor(); await page.goto(chatUrl); await chat.locator('.fmi-chat__label').getByText('合成・編集支援AI', {exact: true}).waitFor(); assert.equal(await assistants().count(), 0);
    await page.goto(settingsUrl); await page.locator('#fmi-staff-agent').selectOption('synthetic-internal'); await page.locator('#fmi-personal-status').getByText('AIの選択を保存しました。').waitFor(); await page.goto(chatUrl); await chat.locator('.fmi-chat__label').getByText('合成・運営支援AI', {exact: true}).waitFor(); assert.equal(await assistants().count(), previous); checked('AIごとの会話を分離して復元');
    await page.reload(); await input().waitFor(); assert.equal(await chat.locator('.fmi-chat__label').textContent(), '合成・運営支援AI'); checked('AI選択と本人セッションの復元');
    page.on('dialog', (dialog) => dialog.accept()); await chat.getByRole('button', {name: '新しい相談'}).click(); await chat.getByText('新しい相談を始められます。').waitFor(); assert.equal(await assistants().count(), 0); checked('新しい相談で以前の会話を切り離す');
    const guest = await browser.newContext({viewport: {width: 1365, height: 1000}, colorScheme: 'light'});
    const publicPage = await guest.newPage(); publicPage.on('pageerror', (error) => errors.push(error.message)); await publicPage.goto(fixture.url);
    const publicChat = publicPage.locator('.fmi-chat'); const publicInput = publicChat.locator('textarea'); await publicInput.waitFor();
    let response = null;
    await publicPage.evaluate(() => { const stream = window.FourmixIntelligenceChat.stream; window.FourmixIntelligenceChat.stream = async (...args) => { const reply = await stream(...args); window.fmiLastReply = reply; return reply; }; });
    const publicSend = async (text) => { const before = await publicChat.locator('.fmi-chat__message--assistant').count(); await publicInput.fill(text); await publicChat.getByRole('button', {name: '送信', exact: true}).click(); await publicPage.waitForFunction((count) => document.querySelectorAll('.fmi-chat .fmi-chat__message--assistant').length > count && document.querySelector('.fmi-chat').getAttribute('aria-busy') === 'false', before); response = await publicPage.evaluate(() => window.fmiLastReply); };
    await publicSend('合成公開・はじめての相談'); await publicSend('長文・公開サイトについて'); assert.equal(await publicChat.locator('.fmi-chat__message--user').count(), 2); assert.ok(response.conversation_id); assert.equal(response.customer_token, undefined); checked('公開チャットの連続会話とトークン非公開');
    assert.equal(await publicChat.locator('.fmi-chat__tool').count(), 0); assert.equal(await publicPage.locator('iframe').count(), 0); checked('WordPressのDOMで公開AIだけを使用');
    const cookie = (await guest.cookies()).find((item) => item.name === 'fourmix_intelligence_visitor'); assert.equal(cookie.httpOnly, true); assert.equal(cookie.sameSite, 'Strict');
    const saved = await publicPage.evaluate(() => JSON.stringify({...sessionStorage, ...localStorage})); assert.equal(saved.includes('customer_token'), false); checked('会話確認情報はHttpOnly訪問者cookieとサーバーに保持');
    await fit(publicPage.locator('body')); await publicPage.locator('.fmi-block').screenshot({path: path.join(output, 'chat-public-desktop.png')}); evidence.push('chat-public-desktop.png');
    await publicPage.evaluate(() => window.scrollTo(0, 0)); await publicPage.screenshot({path: path.join(output, 'chat-public-page-desktop.png')}); evidence.push('chat-public-page-desktop.png');
    await publicPage.setViewportSize({width: 390, height: 844}); await fit(publicPage.locator('body')); await fit(publicChat);
    const sendPlacement = await publicChat.getByRole('button', {name: '送信', exact: true}).boundingBox(), hostPlacement = await publicChat.boundingBox(); assert.ok(sendPlacement.x > hostPlacement.x + hostPlacement.width / 2);
    await publicPage.locator('.fmi-block').screenshot({path: path.join(output, 'chat-public-narrow.png')}); evidence.push('chat-public-narrow.png');
    await publicPage.emulateMedia({colorScheme: 'dark'}); await publicPage.locator('.fmi-block').screenshot({path: path.join(output, 'chat-public-dark-narrow.png')}); evidence.push('chat-public-dark-narrow.png'); checked('公開ページのデスクトップ・狭い画面・暗色表示');
    await publicChat.getByRole('button', {name: '履歴を読み込む'}).click(); await publicChat.getByText('合成履歴です。', {exact: false}).waitFor(); checked('公開履歴を既存APIから取得');
    await publicPage.reload(); await publicInput.waitFor(); await publicChat.getByText('合成履歴です。', {exact: false}).waitFor(); checked('同じ訪問者の再読込で履歴復元');
    await publicInput.fill('合成遅延・公開受信停止'); await publicChat.getByRole('button', {name: '送信', exact: true}).click(); await publicChat.getByRole('button', {name: '受信を停止'}).click();
    await publicChat.getByText('受信を停止しました。', {exact: false}).waitFor(); await publicPage.waitForTimeout(3500); await publicChat.getByRole('button', {name: '送信結果を確認'}).click(); await publicChat.getByText('応答を受け取りました。', {exact: true}).waitFor(); checked('公開会話も受信停止後に結果を照会');
    publicPage.on('dialog', (dialog) => dialog.accept()); await publicChat.getByRole('button', {name: '新しい相談'}).click(); await publicChat.getByText('新しい相談を始められます。').waitFor();
    assert.equal(await publicChat.locator('.fmi-chat__message').count(), 0); checked('公開会話で新しい相談を作成');
    const other = await browser.newContext(); const otherPage = await other.newPage(); await otherPage.goto(fixture.url); await otherPage.locator('.fmi-chat textarea').waitFor();
    assert.equal(await otherPage.locator('.fmi-chat__message').count(), 0); checked('別訪問者へ会話を表示しない'); await other.close();
    assert.deepEqual(errors, []); checked('JavaScript例外なし');
    const report = {environment: '本機Edge・既存ローカルWordPress、Studioと操作実行の応答は合成、モデル未使用', checks, screenshots: evidence, errors};
    fs.writeFileSync(path.join(output, 'chat-ui-results.json'), JSON.stringify(report, null, 2)); console.log(JSON.stringify({checks: checks.length, screenshots: evidence.length, errors}, null, 2));
  } catch (error) { if (currentPage) { await currentPage.screenshot({path: path.join(output, 'chat-ui-failure.png'), fullPage: true}); console.error('画面の状態:', await currentPage.locator('#fmi-result, .fmi-chat__status').allTextContents()); } throw error;
  } finally { await browser.close(); }
})().catch((error) => { console.error(error.stack); process.exitCode = 1; });
