/* 本機Edgeと既存WordPressで検証。中央AI・操作結果だけは合成応答です。 */
const fs = require('node:fs');
const path = require('node:path');
const assert = require('node:assert/strict');
const {execFileSync} = require('node:child_process');
const {chromium} = require(process.env.FMI_PLAYWRIGHT_MODULE || '../../../app/node_modules/playwright');
const fixture = JSON.parse(fs.readFileSync(process.argv[2], 'utf8').replace(/^\uFEFF/, ''));
const output = process.argv[3] || path.resolve(__dirname, '../docs/evidence');
const root = path.resolve(__dirname, '../../../..');
const base = 'http://localhost:48093/wp-admin/';
const settings = base + 'admin.php?page=fourmix-intelligence-personal-settings';
const pageChat = base + 'admin.php?page=fourmix-intelligence-operations&post_id=' + fixture.draft_id;
const runtimeOverride = path.join(root, '.local/wordpress-runtime.compose.yaml');
const composeFiles = ['-f', 'compose.yaml', '-f', 'compose.extensions.yaml', ...(fs.existsSync(runtimeOverride) ? ['-f', runtimeOverride] : [])];
const cli = (...args) => execFileSync('docker', ['compose', ...composeFiles, 'run', '--rm', '--no-deps', '--entrypoint', 'wp', 'wordpress-init', 'eval-file', '/var/www/html/wp-content/plugins/fourmix-intelligence/tests/chat-ui-fixture.php', ...args], {cwd: root, encoding: 'utf8', timeout: 30000, stdio: ['ignore', 'pipe', 'pipe']});
const inspect = () => JSON.parse(cli('inspect'));
fs.mkdirSync(output, {recursive: true});
(async () => {
  const browser = await chromium.launch({channel: 'msedge', headless: true});
  const checks = [], screenshots = [], errors = [], requests = [];
  const checked = (name) => { checks.push(name); console.log(name); };
  let page;
  try {
    const context = await browser.newContext({viewport: {width: 1365, height: 1000}, colorScheme: 'light'});
    await context.addCookies(fixture.cookies); context.setDefaultTimeout(12000);
    page = await context.newPage(); page.on('pageerror', (error) => errors.push(error.message));
    page.on('request', (request) => { if (request.url().includes('/staff/')) requests.push({action: request.url().split('/').pop(), body: request.postDataJSON()}); });
    const dock = page.locator('#fmi-dock-panel'), chat = () => page.locator('.fmi-staff-surface .fmi-chat');
    const input = () => chat().locator('textarea'), assistants = () => chat().locator('.fmi-chat__message--assistant');
    const send = async (text) => { const count = await assistants().count(); await input().fill(text); await chat().getByRole('button', {name: '送信', exact: true}).click(); await page.waitForFunction((before) => document.querySelectorAll('.fmi-staff-surface .fmi-chat__message--assistant').length > before && document.querySelector('.fmi-staff-surface .fmi-chat').getAttribute('aria-busy') === 'false', count); };
    const shot = async (name) => { await page.screenshot({path: path.join(output, name)}); screenshots.push(name); };
    const fit = async () => {
      const bounds = await dock.boundingBox(); const size = page.viewportSize();
      assert.ok(bounds.x >= 0 && bounds.y >= 32 && bounds.x + bounds.width <= size.width + 1 && bounds.y + bounds.height <= size.height, JSON.stringify(bounds));
      assert.ok(await input().isVisible()); const box = await input().boundingBox(); assert.ok(box.y >= bounds.y && box.y + box.height < bounds.y + bounds.height);
      const overflow = await dock.evaluate((el) => ({width: el.clientWidth, scroll: el.scrollWidth})); assert.ok(overflow.scroll <= overflow.width + 1, JSON.stringify(overflow));
      const log = await chat().locator('.fmi-chat__messages').boundingBox(); assert.ok(log.height >= 60, JSON.stringify(log));
    };
    await page.goto(base); await page.locator('#fmi-dock-toggle').waitFor();
    const scope = await page.evaluate(() => window.FourmixIntelligenceStaff.uiScope); cli('expire-personal', scope);
    assert.equal(await dock.isVisible(), false); assert.equal(requests.length, 0); checked('業務画面では開くまでAIの通信をしない');
    await page.locator('#fmi-dock-toggle').click(); await dock.getByRole('link', {name: '本人のAI設定を開く'}).waitFor();
    assert.equal(await dock.locator('input[type="password"],select').count(), 0); checked('未設定の浮窓は短い案内と設定へのリンクだけ');
    await shot('dock-unconfigured.png'); await page.locator('#fmi-dock-close').click();
    await page.goto(settings); await page.locator('#fmi-personal-token').fill('synthetic-ui-personal-token'); await page.getByRole('button', {name: 'AI一覧を取得'}).click();
    await page.locator('#fmi-personal-status').getByText('本人のAIに接続しました。').waitFor();
    await page.locator('#fmi-staff-agent').selectOption('synthetic-internal'); await page.locator('#fmi-personal-status').getByText('AIの選択を保存しました。').waitFor();
    assert.equal(await page.locator('#fmi-personal-token').inputValue(), ''); assert.equal(await page.getByRole('link', {name: 'サイト全体の連携設定', exact: true}).count(), 0);
    await shot('dock-personal-settings.png'); checked('投稿者も本人設定を利用でき、サイト管理者の設定は表示しない');
    await page.goto(base); const startCatalog = requests.filter((item) => item.action === 'catalog').length;
    await page.locator('#fmi-dock-toggle').click(); await input().waitFor();
    await page.locator('#fmi-dock-toggle').evaluate((el) => { for (let i = 0; i < 30; i++) el.click(); });
    assert.equal(await dock.isVisible(), true); assert.equal(await page.locator('.fmi-staff-surface').count(), 1);
    assert.equal(requests.filter((item) => item.action === 'catalog').length - startCatalog, 1); checked('浮窓を30回切り替えても会話と初期化は一つ');
    const sourceHash = require('node:crypto').createHash('sha256').update(fs.readFileSync(path.resolve(root, 'services/app/packages/platform-app/src/assets/brand/fourmix-intelligence-shopify-icon-1200.png'))).digest('hex');
    const copyHash = require('node:crypto').createHash('sha256').update(fs.readFileSync(path.resolve(__dirname, '../assets/brand/fourmix-intelligence-icon.png'))).digest('hex'); assert.equal(copyHash, sourceHash);
    const brand = await page.locator('#fmi-dock-toggle img').evaluate((el) => ({width: el.naturalWidth, height: el.naturalHeight, filter: getComputedStyle(el).filter, opacity: getComputedStyle(el).opacity}));
    assert.deepEqual(brand, {width: 1200, height: 1200, filter: 'none', opacity: '1'}); checked('指定ブランド画像のバイトを維持し、色や透明度を変更しない');
    await send('長文・ダッシュボード浮窓'); assert.equal(inspect().last_body.options.native_context.record, undefined); assert.equal(inspect().last_body.options.native_context.screen, undefined);
    await fit(); await shot('dock-dashboard-desktop.png'); checked('長文は浮窓内でスクロールし入力領域を残す');
    assert.equal(await page.locator('#fmi-include-context').isChecked(), false); await page.locator('#fmi-include-context').check(); await send('合成画面名・ダッシュボード');
    const dashboard = inspect().last_body.options.native_context; assert.equal(dashboard.screen.id, 'dashboard'); assert.equal(dashboard.record, undefined); checked('選択時だけ現在の画面名を参考情報として送信');
    await page.getByRole('link', {name: 'Profile', exact: true}).first().click(); await input().waitFor(); assert.equal(await dock.isVisible(), true); assert.equal(await page.locator('#fmi-include-context').isChecked(), false);
    assert.ok(await assistants().count() >= 2); checked('通常の管理画面リンクで移動しても浮窓と会話を復元');
    await page.goBack(); await input().waitFor(); assert.equal(await dock.isVisible(), true); assert.ok(await assistants().count() >= 2); checked('戻る操作でも会話を復元し再送しない');
    const delayedBefore = requests.filter((item) => item.action === 'chat_stream').length;
    await input().fill('合成遅延・閉じても続行'); await chat().getByRole('button', {name: '送信', exact: true}).click(); await page.locator('#fmi-dock-close').click();
    assert.equal(await dock.isVisible(), false); await page.waitForTimeout(3500); await page.locator('#fmi-dock-toggle').click(); await assistants().filter({hasText: 'ご相談を受け付けました: 合成遅延・閉じても続行'}).waitFor(); await page.waitForFunction(() => document.querySelector('.fmi-staff-surface .fmi-chat').getAttribute('aria-busy') === 'false');
    assert.equal(requests.filter((item) => item.action === 'chat_stream').length - delayedBefore, 1); checked('送信中に閉じて再度開いても依頼を再実行しない');
    await input().press('Escape'); assert.equal(await dock.isVisible(), false); assert.equal(await page.locator('#fmi-dock-toggle').evaluate((el) => el === document.activeElement), true); checked('Escで閉じて入口にフォーカスを戻す');
    await page.goto(pageChat); await input().waitFor(); assert.equal(await page.locator('#fmi-chat-page input[type="password"], #fmi-chat-page select, #fmi-operation').count(), 0);
    await input().fill('まだ送信していない入力'); const typed = await input().inputValue(); const beforeMove = requests.filter((item) => item.action === 'session').length;
    await page.locator('#fmi-dock-toggle').click(); assert.equal(await page.locator('#fmi-chat-page .fmi-chat').count(), 0); assert.equal(await dock.locator('.fmi-chat').count(), 1); assert.equal(await input().inputValue(), typed);
    await page.locator('#fmi-dock-close').click(); assert.equal(await page.locator('#fmi-chat-page .fmi-chat').count(), 1); assert.equal(await input().inputValue(), typed); assert.equal(requests.filter((item) => item.action === 'session').length, beforeMove); checked('ページ式と浮窓は同じDOMを移動し未送信入力を維持');
    await page.locator('#fmi-include-context').check(); await send('合成投稿文脈・浮窓'); const record = inspect().last_body.options.native_context.record;
    assert.equal(record.id, fixture.draft_id); assert.equal(record.content, undefined); checked('投稿文脈は対象権限を再確認し本文を含めない');
    await page.locator('#fmi-dock-toggle').click(); await send('合成操作・浮窓の確認'); const tool = chat().locator('.fmi-chat__tool').last();
    await tool.getByRole('button', {name: '内容を確認して実行'}).click(); await tool.getByText('実行済み', {exact: true}).waitFor(); assert.equal(inspect().actions[await tool.getAttribute('data-action-id')].posts, 1); checked('浮窓も正式プレビューと明示確認の同じ経路を利用');
    await send('合成不明操作・浮窓'); const unknown = chat().locator('.fmi-chat__tool').last(); await unknown.getByRole('button', {name: '内容を確認して実行'}).click(); await unknown.getByText('結果不明。', {exact: false}).waitFor();
    await unknown.getByRole('button', {name: '実行結果を確認'}).click(); assert.equal(inspect().actions[await unknown.getAttribute('data-action-id')].posts, 1); checked('浮窓の結果不明も承認を再送せず照会する');
    await chat().locator('.fmi-chat__messages').evaluate((el) => { el.scrollTop = el.scrollHeight; }); await fit(); await shot('dock-tool-desktop.png'); await page.setViewportSize({width: 390, height: 844}); await fit(); await shot('dock-tool-narrow.png');
    await page.emulateMedia({colorScheme: 'dark'}); await fit(); await shot('dock-tool-dark-narrow.png'); checked('390pxと暗色でも入力・確認・閉じる操作が収まる');
    await page.setViewportSize({width: 390, height: 500}); await fit(); await shot('dock-short-viewport.png'); checked('高さ500pxでは補助表示を縮めて会話と入力を残す');
    await page.setViewportSize({width: 1365, height: 1000}); await page.emulateMedia({colorScheme: 'light'}); await page.goto(base + 'edit.php'); await input().waitFor();
    await page.locator('#fmi-dock-close').click(); await page.locator('#bulk-action-selector-top').selectOption('edit'); assert.equal(await page.locator('#bulk-action-selector-top').inputValue(), 'edit'); checked('閉じた浮窓は投稿一覧の操作を遮らない');
    await page.locator('#fmi-dock-toggle').click(); await page.locator('#fmi-include-context').check(); await send('合成一覧画面・参考情報'); const list = inspect().last_body.options.native_context; assert.equal(list.screen.id, 'edit-post'); assert.equal(list.record, undefined); checked('一覧画面の行データをAIへ送信しない');
    await page.goto(base + 'post.php?post=' + fixture.draft_id + '&action=edit'); await input().waitFor(); assert.equal(await page.evaluate(() => window.FourmixIntelligenceStaff.context.post_id), fixture.draft_id);
    const welcome = page.getByRole('dialog').filter({hasText: 'Welcome to the editor'}); await welcome.waitFor({state: 'visible', timeout: 3000}).catch(() => {}); if (await welcome.isVisible()) { await welcome.getByRole('button', {name: 'Close', exact: true}).click(); await welcome.waitFor({state: 'hidden'}); await page.locator('.components-modal__screen-overlay').waitFor({state: 'hidden'}); }
    await input().fill('編集画面からの相談'); await shot('dock-native-editor.png'); checked('WordPressの投稿編集画面でも浮窓が利用可能');
    await page.goto(base + 'admin.php?page=fourmix-intelligence-native-operations'); await page.locator('#fmi-action option').first().waitFor({state: 'attached'}); assert.ok(await page.locator('#fmi-action option').count() > 0); checked('直接業務操作は専用ページへ移し既存カタログを維持');
    await page.goto(base); await input().waitFor(); await page.evaluate(() => { window.FourmixIntelligenceStaff.nonce = 'expired-synthetic-nonce'; });
    await input().fill('合成権限失効'); await chat().getByRole('button', {name: '送信', exact: true}).click(); await dock.getByRole('link', {name: '本人のAI設定を開く'}).waitFor(); assert.equal(await dock.locator('textarea').count(), 0); checked('WordPress認証の失効時は会話入力を閉じ設定へ案内');
    await page.reload(); await input().waitFor(); cli('expire-personal', scope);
    await chat().getByRole('button', {name: '新しい相談'}).evaluate((el) => { window.confirm = () => true; el.click(); }); await dock.getByRole('link', {name: '本人のAI設定を開く'}).waitFor(); assert.equal(await dock.locator('textarea').count(), 0); checked('本人接続の期限切れは新しい会話を作らず再設定へ案内');
    const guest = await browser.newContext(); const publicPage = await guest.newPage(); await publicPage.goto(fixture.url); await publicPage.locator('.fmi-chat textarea').waitFor();
    assert.equal(await publicPage.locator('#fmi-dock, .fmi-staff-surface').count(), 0); assert.equal(await publicPage.locator('.fmi-block__header img[alt="Fourmix Intelligence"]').count(), 1); checked('匿名公開画面には社内浮窓を出さず公式ブランドを表示'); await guest.close();
    const raw = await page.evaluate(() => JSON.stringify({...localStorage, ...sessionStorage})); assert.equal(raw.includes('synthetic-ui-personal-token'), false); checked('本人トークンをブラウザー保存へ残さない');
    assert.deepEqual(errors, []); checked('全経路でJavaScript例外なし');
    fs.writeFileSync(path.join(output, 'dock-ui-results.json'), JSON.stringify({environment: '本機Edge・既存WordPress。中央Studioとツール応答は合成。CUA操作、実モデル、実中央更新は未実施。', brandSha256: copyHash, checks, screenshots, errors}, null, 2));
    console.log(JSON.stringify({checks: checks.length, screenshots: screenshots.length, errors}));
  } catch (error) { if (page) { await page.screenshot({path: path.join(output, 'dock-ui-failure.png')}); console.error('画面状態:', await page.locator('.fmi-chat__status,.fmi-staff-setup').allTextContents()); } throw error; }
  finally { await browser.close(); }
})().catch((error) => { console.error(error.stack); process.exitCode = 1; });
