/* 本機Edge・実WP REST・独立した合成HTTPで、逐次転送と会話添付を検証します。 */
const fs = require('node:fs'), path = require('node:path'), assert = require('node:assert/strict');
const {execFileSync} = require('node:child_process');
const {chromium} = require(process.env.FMI_PLAYWRIGHT_MODULE || '../../../app/node_modules/playwright');
const fixture = JSON.parse(fs.readFileSync(process.argv[2], 'utf8').replace(/^\uFEFF/, ''));
const output = process.argv[3] || path.resolve(__dirname, '../docs/evidence'); fs.mkdirSync(output, {recursive: true});
const base = 'http://localhost:48093/wp-admin/', pageUrl = base + 'admin.php?page=fourmix-intelligence-operations&post_id=' + fixture.draft_id;
const metrics = () => JSON.parse(execFileSync('docker', ['exec', 'fourmix-wp-rich-fixture', 'cat', '/tmp/fourmix-wordpress-rich-fixture.json'], {encoding: 'utf8'}));
const png = Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+j5f8AAAAASUVORK5CYII=', 'base64');
(async () => {
  const browser = await chromium.launch({channel: 'msedge', headless: true}); let page;
  const checks = [], screenshots = [], errors = [];
  const checked = (name) => { checks.push(name); console.log(name); };
  try {
    const context = await browser.newContext({viewport: {width: 1365, height: 1000}}); await context.addCookies(fixture.cookies); context.setDefaultTimeout(15000);
    page = await context.newPage(); page.on('pageerror', (error) => errors.push(error.message));
    await page.addInitScript(() => { Object.defineProperty(navigator, 'clipboard', {value: {writeText: async (text) => { window.fmiCopied = text; }}, configurable: true}); });
    await page.goto(base + 'admin.php?page=fourmix-intelligence-personal-settings');
    await page.locator('#fmi-personal-token').fill('synthetic-ui-personal-token'); await page.getByRole('button', {name: 'AI一覧を取得'}).click(); await page.locator('#fmi-personal-status').getByText('本人のAIに接続しました。').waitFor();
    await page.locator('#fmi-staff-agent').selectOption('synthetic-internal'); await page.locator('#fmi-personal-status').getByText('AIの選択を保存しました。').waitFor(); await page.goto(pageUrl);
    const chat = () => page.locator('.fmi-staff-surface .fmi-chat'), input = () => chat().locator('textarea'); await input().waitFor();
    const settled = async () => { await page.waitForFunction(() => document.querySelector('.fmi-staff-surface .fmi-chat')?.getAttribute('aria-busy') === 'false' && !document.querySelector('.fmi-staff-surface .fmi-chat__controls button[type="submit"]').disabled); };
    const send = async (text) => { await input().fill(text); await chat().getByRole('button', {name: '送信', exact: true}).click(); await settled(); };
    const shot = async (name) => { await page.screenshot({path: path.join(output, name)}); screenshots.push(name); };
    await page.evaluate(() => { const stream = window.FourmixIntelligenceChat.stream; window.fmiEvents = []; window.FourmixIntelligenceChat.stream = (url, init, signal, receive) => stream(url, init, signal, (event) => { window.fmiEvents.push({type: event.type, at: performance.now(), data: event.data}); receive(event); }); });
    await input().fill('合成リッチ・逐次受信'); await chat().getByRole('button', {name: '送信', exact: true}).click(); await chat().getByRole('heading', {name: '業務の確認結果'}).waitFor();
    assert.equal(await chat().getAttribute('aria-busy'), 'true'); assert.equal(await page.evaluate(() => window.fmiEvents.some((event) => event.type === 'run.completed')), false); checked('完了前にHTTP断片から見出しと表を表示');
    await settled(); const timing = await page.evaluate(() => { const events = window.fmiEvents; return {first: events.find((event) => event.type === 'assistant.delta').at, last: events.find((event) => event.type === 'run.completed').at}; });
    assert.ok(timing.last - timing.first > 1200, JSON.stringify(timing)); checked('逐次イベントと完了の時間差を実測し一括応答の再生をしない');
    const eventData = await page.evaluate(() => JSON.stringify(window.fmiEvents)); assert.equal(eventData.includes('customer_token'), false); assert.equal(eventData.includes('synthetic-private-run-ticket'), false); checked('逐次イベントから会話の秘密と実行ticketを再帰的に除外');
    assert.ok(await chat().locator('strong').filter({hasText: '強調'}).count()); assert.ok(await chat().locator('em').count()); assert.ok(await chat().locator('s').count()); assert.ok(await chat().locator('blockquote').count()); assert.ok(await chat().locator('li').count()); checked('強調・取り消し・引用・リストを安全なMarkdownで表示');
    assert.equal(await chat().locator('table tbody tr').count(), 2); await chat().getByRole('button', {name: '表をコピー'}).click(); assert.ok((await page.evaluate(() => window.fmiCopied)).includes('業務\t状態'));
    await chat().getByRole('button', {name: 'コピー', exact: true}).first().click(); assert.ok((await page.evaluate(() => window.fmiCopied)).includes('const approved')); assert.ok(await chat().locator('.hljs-keyword').count()); checked('表のTSVコピーとコードコピー・構文色分け');
    await chat().locator('iframe.fmi-answer-diagram').waitFor(); await chat().frameLocator('iframe.fmi-answer-diagram').locator('svg').waitFor();
    assert.equal(await chat().locator('iframe.fmi-answer-diagram').getAttribute('sandbox'), ''); assert.ok((await chat().locator('iframe.fmi-answer-diagram').getAttribute('srcdoc')).includes("default-src &#39;none&#39;")); checked('Mermaidをstrict設定と無権限sandbox・CSP内で実描画');
    await chat().getByRole('button', {name: '図を拡大'}).click(); await page.locator('dialog[open] iframe').waitFor(); await shot('rich-diagram-expanded.png'); await page.locator('dialog[open]').getByRole('button', {name: '閉じる'}).click(); checked('図の拡大と閉じる操作');
    await chat().locator('.fmi-chat__messages').evaluate((el) => { el.scrollTop = 0; }); await shot('rich-page-desktop.png');
    await page.locator('#fmi-dock-toggle').click(); await page.setViewportSize({width: 390, height: 844});
    const tableBounds = await chat().locator('.fmi-answer-table').evaluate((el) => ({width: el.clientWidth, scroll: el.scrollWidth})); assert.ok(tableBounds.scroll > tableBounds.width);
    const dockBounds = await page.locator('#fmi-dock-panel').evaluate((el) => ({width: el.clientWidth, scroll: el.scrollWidth})); assert.ok(dockBounds.scroll <= dockBounds.width + 1);
    await chat().locator('.fmi-answer-table').evaluate((el) => { el.scrollLeft = el.scrollWidth; el.scrollIntoView({block: 'center'}); }); await shot('rich-table-narrow.png'); checked('390pxで表だけを横スクロールし浮窓やページを広げない');
    await page.emulateMedia({colorScheme: 'dark'}); await chat().locator('.fmi-chat__messages').evaluate((el) => { el.scrollTop = el.scrollHeight; }); await shot('rich-diagram-dark-narrow.png'); checked('暗色でも表・コード・図を表示');
    await page.setViewportSize({width: 1365, height: 1000}); await page.emulateMedia({colorScheme: 'light'});
    let externalImages = 0; await page.route('https://example.test/**', (route) => { externalImages++; route.abort(); }); await send('合成禁止図・安全な表示');
    await chat().getByText('図の設定またはサイズを確認してください。', {exact: true}).waitFor(); assert.equal(await page.evaluate(() => window.fmiInjected), undefined); assert.equal(await chat().locator('a[href^="javascript:"]').count(), 0); assert.equal(externalImages, 0); checked('図の設定上書き・スクリプト・危険リンク・外部画像自動取得を拒否');
    const fileInput = () => chat().locator('input[type="file"]');
    await fileInput().setInputFiles({name: '合成遅延添付.txt', mimeType: 'text/plain', buffer: Buffer.from('合成の業務資料です。ユーザーの実データは含めません。')}); await chat().locator('.fmi-attachments progress').waitFor(); assert.equal(await chat().getByRole('button', {name: '送信', exact: true}).isDisabled(), true);
    await chat().getByText('添付の保存を確認しました', {exact: true}).waitFor(); checked('ファイルの実multipart転送・進捗・保存待ちを表示し送信を保留');
    const beforeDelete = metrics().deletes; await chat().locator('.fmi-attachments').getByRole('button', {name: '取り除く'}).click(); await page.waitForFunction(() => document.querySelectorAll('.fmi-attachments-list .fmi-attachment').length === 0); assert.equal(metrics().deletes, beforeDelete + 1); checked('未送信添付の取り除きは中央の専用DELETEで確認');
    await fileInput().setInputFiles({name: '合成画像.png', mimeType: 'image/png', buffer: png}); await chat().locator('.fmi-attachments img').waitFor(); await chat().getByText('添付の保存を確認しました', {exact: true}).waitFor();
    await shot('rich-attachment-preview.png'); await chat().getByRole('button', {name: '送信', exact: true}).click(); await settled(); assert.equal(metrics().last_body.messages[0].attachment_ids.length, 1); await chat().locator('.fmi-message-image').waitFor(); checked('画像プレビューと添付だけの依頼を既存attachment_idsで送信');
    await page.reload(); await input().waitFor(); await chat().locator('.fmi-message-image').waitFor(); assert.equal(await chat().locator('.fmi-attachments-list .fmi-attachment').count(), 0); checked('再読込で送信済み画像を本人の非公開content APIから復元');
    const blockedBefore = metrics().uploads;
    await fileInput().setInputFiles({name: '禁止.svg', mimeType: 'image/svg+xml', buffer: Buffer.from('<svg onload="alert(1)"></svg>')}); await chat().getByText('形式またはサイズの上限を確認してください。', {exact: false}).waitFor(); assert.equal(metrics().uploads, blockedBefore);
    await fileInput().setInputFiles({name: '過大.txt', mimeType: 'text/plain', buffer: Buffer.alloc(2 * 1024 * 1024 + 1, 'a')}); assert.equal(metrics().uploads, blockedBefore); checked('非対応形式と過大ファイルはブラウザーと受付ポリシーで拒否');
    await fileInput().setInputFiles({name: '偽画像.png', mimeType: 'image/png', buffer: Buffer.from('<script>not an image</script>')}); await chat().locator('.fmi-attachments-status').getByText('画像の形式または大きさを確認してください。', {exact: true}).waitFor(); assert.equal(metrics().uploads, blockedBefore); await chat().locator('.fmi-attachments').getByRole('button', {name: '取り除く'}).click(); checked('拡張子を偽った画像はWPサーバーでも拒否');
    let failed = false; await page.route('**/staff/attachment_upload', async (route) => { if (!failed) { failed = true; await route.abort('failed'); } else await route.continue(); });
    await fileInput().setInputFiles({name: '合成未到達.txt', mimeType: 'text/plain', buffer: Buffer.from('合成未到達の資料')}); await chat().locator('.fmi-attachments').getByRole('button', {name: '送信結果を確認'}).waitFor();
    await chat().locator('.fmi-attachments').getByRole('button', {name: '送信結果を確認'}).click(); await chat().locator('.fmi-attachments').getByRole('button', {name: '再試行'}).click(); await chat().getByText('添付の保存を確認しました', {exact: true}).waitFor(); await page.unroute('**/staff/attachment_upload'); checked('未到達を照会した添付だけを同じ確認IDで再試行');
    await chat().locator('.fmi-attachments').getByRole('button', {name: '取り除く'}).click(); await page.waitForFunction(() => document.querySelectorAll('.fmi-attachments-list .fmi-attachment').length === 0);
    const unknownBefore = metrics().uploads; await page.route('**/staff/attachment_upload', async (route) => { await route.fetch(); await route.abort('failed'); });
    await fileInput().setInputFiles({name: '合成保存後通信断.txt', mimeType: 'text/plain', buffer: Buffer.from('合成保存を確認する資料')}); await chat().locator('.fmi-attachments').getByRole('button', {name: '送信結果を確認'}).waitFor(); await chat().locator('.fmi-attachments').getByRole('button', {name: '送信結果を確認'}).click(); await chat().getByText('添付の保存を確認しました', {exact: true}).waitFor(); assert.equal(metrics().uploads, unknownBefore + 1); await page.unroute('**/staff/attachment_upload'); checked('保存後の通信断は保存済み結果を復元し再アップロードしない');
    await send('合成の添付資料を確認してください'); await shot('rich-attachment-message.png');
    const guest = await browser.newContext({viewport: {width: 390, height: 844}}), publicPage = await guest.newPage(); publicPage.on('pageerror', (error) => errors.push(error.message)); await publicPage.goto(fixture.url);
    const publicChat = publicPage.locator('.fmi-chat'); await publicChat.locator('input[type="file"]').waitFor({state: 'attached'});
    await publicChat.locator('input[type="file"]').setInputFiles({name: '合成公開資料.txt', mimeType: 'text/plain', buffer: Buffer.from('公開訪問者専用の合成ファイル')}); await publicChat.getByText('添付の保存を確認しました', {exact: true}).waitFor();
    await publicChat.locator('textarea').fill('合成公開・添付の相談'); await publicChat.getByRole('button', {name: '送信', exact: true}).click(); await publicChat.getByText('応答を受け取りました。', {exact: true}).waitFor(); assert.equal(metrics().last_body.messages[0].attachment_ids.length, 1); checked('匿名公開添付はcustomer-conversationと秘密確認ヘッダーで所有を照合');
    const publicState = await publicPage.evaluate(() => { const key = Object.keys(sessionStorage).find((key) => key.startsWith('fourmix_intelligence_chat_v3_')); return JSON.parse(sessionStorage.getItem(key)); });
    const other = await browser.newContext(), otherPage = await other.newPage(); await otherPage.goto(fixture.url); await otherPage.locator('.fmi-chat textarea').waitFor();
    const denied = await otherPage.evaluate(async (value) => { const reply = await fetch(window.FourmixIntelligenceSettings.attachmentEndpoint + 'attachment_content', {method: 'POST', headers: {'Content-Type': 'application/json'}, body: JSON.stringify({conversation_id: value.conversation_id, id: value.messages[0].attachments[0].id})}); return reply.status; }, publicState); assert.equal(denied, 403); checked('別訪問者は会話IDと添付IDを持ち込んでも内容を取得しない');
    const internalDenied = await otherPage.evaluate(async () => { const reply = await fetch('/wp-json/fourmix-intelligence/v1/staff/attachment_list', {method: 'POST', headers: {'Content-Type': 'application/json'}, body: '{}'}); return reply.status; }); assert.ok([401, 403].includes(internalDenied)); checked('匿名訪問者が社内添付APIへ入れない'); await other.close();
    const publicStorage = await publicPage.evaluate(() => JSON.stringify({...sessionStorage, ...localStorage})); assert.equal(publicStorage.includes('customer_token'), false); assert.equal(publicStorage.includes('synthetic-private-run-ticket'), false); checked('公開の逐次イベント・保存に会話秘密や実行ticketを含めない');
    await publicPage.locator('.fmi-block').screenshot({path: path.join(output, 'rich-public-attachment-narrow.png')}); screenshots.push('rich-public-attachment-narrow.png'); await guest.close();
    assert.deepEqual(errors, []); checked('JavaScript例外なし');
    const result = {environment: '本機Edge・実WordPress HTTP/REST・独立ローカル合成HTTP。実Studio/モデル・中央業務更新・実ユーザーファイルは未使用。コピー先はブラウザー内の合成Clipboard。', checks, screenshots, errors, streamingTiming: {firstDeltaMs: timing.first, completedMs: timing.last, differenceMs: timing.last - timing.first}};
    fs.writeFileSync(path.join(output, 'rich-ui-results.json'), JSON.stringify(result, null, 2)); console.log(JSON.stringify({checks: checks.length, screenshots: screenshots.length, errors}));
  } catch (error) { if (page) { await page.screenshot({path: path.join(output, 'rich-ui-failure.png')}); console.error('画面状態:', await page.locator('.fmi-chat__status,.fmi-attachments-status').allTextContents()); } throw error; }
  finally { await browser.close(); }
})().catch((error) => { console.error(error.stack); process.exitCode = 1; });
